/**
 * AutoDoc Tool Handlers
 *
 * Handlers for automatic documentation generation and management.
 * AutoDoc is enabled only when .autodoc folder exists in project root.
 *
 * Handlers:
 * - autodoc_init
 * - autodoc_save
 * - autodoc_get
 * - autodoc_search
 * - autodoc_validate
 * - autodoc_status
 * - autodoc_sync
 * - autodoc_generate
 * - autodoc_changelog
 * - autodoc_install_hooks
 * - autodoc_detect_language
 */

import { join } from "node:path";
import { BaseToolHandler, type ToolResult } from "../base-tool-handler.js";
import {
  AutoDocChangelogSchema,
  AutoDocDetectLanguageSchema,
  AutoDocGenerateSchema,
  AutoDocGetSchema,
  AutoDocInitSchema,
  AutoDocInstallHooksSchema,
  AutoDocSaveSchema,
  AutoDocSearchSchema,
  AutoDocStatusSchema,
  AutoDocSyncSchema,
  AutoDocValidateSchema,
} from "../schemas/autodoc-schemas.js";
import type { z } from "zod";

// =============================================================================
// HELPER: Check if AutoDoc is available
// =============================================================================

async function getAutoDocManagerFromContext(context: any): Promise<any | null> {
  const container = context.getServiceContainer?.();
  if (!container) {
    return null;
  }
  return container.getAutoDocManager();
}

function autodocNotEnabledResult(): ToolResult {
  return {
    content: [
      {
        type: "text",
        text: JSON.stringify({
          success: false,
          error: "AutoDoc not enabled. Create .autodoc folder in project root to enable.",
        }),
      },
    ],
  };
}

// =============================================================================
// AUTODOC INIT
// =============================================================================

export class AutoDocInitToolHandler extends BaseToolHandler<z.infer<typeof AutoDocInitSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocInitSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocInitSchema>): Promise<ToolResult> {
    const container = this.context.getServiceContainer?.();
    if (!container) {
      return autodocNotEnabledResult();
    }

    const adm = await container.getAutoDocManager();
    if (!adm) {
      return autodocNotEnabledResult();
    }

    adm.setConfig({
      enabled: args.enabled,
      language: args.language,
      docsDir: args.docsDir || join(container.directory, ".memory_bank"),
    });

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              message: "AutoDoc initialized",
              config: adm.getConfig(),
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC SAVE
// =============================================================================

export class AutoDocSaveToolHandler extends BaseToolHandler<z.infer<typeof AutoDocSaveSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocSaveSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocSaveSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    const normalizedPath = this.context.normalizeInputPath(args.filePath) || args.filePath;
    const savedDocs = await adm.saveDocument(normalizedPath, args.content, {
      type: args.type as any,
      autoGenerated: args.autoGenerated,
    });

    // Write file to disk (bidirectional sync: DB → Disk)
    let fileWritten = false;
    try {
      const { writeDocumentToDisk } = await import("../../autodoc/sync/file-sync.js");
      await writeDocumentToDisk(normalizedPath, args.content);
      fileWritten = true;
    } catch (error) {
      this.context.logger.warn?.(
        "AUTODOC",
        `Failed to write file to disk: ${(error as Error).message}`,
        {},
        this.context.requestId,
      );
    }

    // Generate embeddings for semantic search (if SemanticAgent available)
    let embeddingsGenerated = 0;
    if (savedDocs.length > 0) {
      try {
        const semanticAgent = await this.context.getSemanticAgent();
        const container = this.context.getServiceContainer?.();
        const vectorStore = container?.getGlobalVectorStore?.();

        if (semanticAgent && vectorStore) {
          for (const doc of savedDocs) {
            const textToEmbed = `${doc.title}\n\n${doc.content}`;
            const embedding = await semanticAgent.generateEmbedding(textToEmbed);

            if (embedding) {
              await vectorStore.insert({
                id: doc.id,
                content: textToEmbed.slice(0, 1000),
                vector: embedding,
                metadata: {
                  type: "autodoc",
                  docType: doc.type,
                  filePath: doc.filePath,
                  section: doc.section,
                  title: doc.title,
                },
                createdAt: Date.now(),
              });
              embeddingsGenerated++;
            }
          }
        }
      } catch (error) {
        this.context.logger.warn?.(
          "AUTODOC",
          `Failed to generate embeddings: ${(error as Error).message}`,
          {},
          this.context.requestId,
        );
      }
    }

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              message: `Saved ${savedDocs.length} sections`,
              fileWritten,
              embeddingsGenerated,
              docs: savedDocs.map((d: any) => ({
                id: d.id,
                title: d.title,
                section: d.section,
              })),
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC GET
// =============================================================================

export class AutoDocGetToolHandler extends BaseToolHandler<z.infer<typeof AutoDocGetSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocGetSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocGetSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    if (args.docId) {
      const doc = await adm.getDocument(args.docId);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: !!doc,
                doc: doc || null,
              },
              null,
              2,
            ),
          },
        ],
      };
    }

    if (args.filePath) {
      const normalizedPath = this.context.normalizeInputPath(args.filePath) || args.filePath;
      const docs = await adm.getDocumentsByFile(normalizedPath);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: true,
                count: docs.length,
                docs,
              },
              null,
              2,
            ),
          },
        ],
      };
    }

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ success: false, error: "Provide docId or filePath" }, null, 2),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC SEARCH
// =============================================================================

export class AutoDocSearchToolHandler extends BaseToolHandler<z.infer<typeof AutoDocSearchSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocSearchSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocSearchSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    interface SearchResult {
      id: string;
      title: string;
      filePath: string;
      section: string | null;
      snippet: string;
      score?: number;
      source: "text" | "semantic";
    }

    const searchResults: SearchResult[] = [];

    // Text search
    if (args.mode === "text" || args.mode === "hybrid") {
      const textResults = await adm.searchDocsByText(args.query, args.limit);
      for (const d of textResults) {
        searchResults.push({
          id: d.id,
          title: d.title,
          filePath: d.filePath,
          section: d.section,
          snippet: d.content.slice(0, 200),
          source: "text",
        });
      }
    }

    // Semantic search (if enabled and VectorStore available)
    if (args.mode === "semantic" || args.mode === "hybrid") {
      try {
        const semanticAgent = await this.context.getSemanticAgent();
        const container = this.context.getServiceContainer?.();
        const vectorStore = container?.getGlobalVectorStore?.();

        if (semanticAgent && vectorStore) {
          const queryEmbedding = await semanticAgent.generateEmbedding(args.query);

          if (queryEmbedding) {
            const semanticResults = await vectorStore.search(queryEmbedding, args.limit);

            for (const result of semanticResults) {
              if (result.id.startsWith("doc::")) {
                const doc = await adm.getDocument(result.id);
                if (doc && !searchResults.some((r) => r.id === doc.id)) {
                  searchResults.push({
                    id: doc.id,
                    title: doc.title,
                    filePath: doc.filePath,
                    section: doc.section,
                    snippet: doc.content.slice(0, 200),
                    score: result.similarity,
                    source: "semantic",
                  });
                }
              }
            }
          }
        }
      } catch (error) {
        this.context.logger.warn?.(
          "AUTODOC",
          `Semantic search failed: ${(error as Error).message}`,
          {},
          this.context.requestId,
        );
      }
    }

    // Sort by score (semantic results first if hybrid)
    searchResults.sort((a, b) => (b.score ?? 0) - (a.score ?? 0));

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              query: args.query,
              mode: args.mode || "text",
              resultsCount: searchResults.length,
              results: searchResults.slice(0, args.limit),
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC VALIDATE
// =============================================================================

export class AutoDocValidateToolHandler extends BaseToolHandler<z.infer<typeof AutoDocValidateSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocValidateSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocValidateSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    const validation = await adm.validateReferences();

    const result: any = {
      success: true,
      total: validation.total,
      valid: validation.valid,
      broken: validation.broken.length,
    };

    if (args.filePath) {
      const normalizedPath = this.context.normalizeInputPath(args.filePath) || args.filePath;
      result.brokenInFile = validation.broken.filter(
        (b: any) => b.ref.sourceLocation.filePath === normalizedPath,
      );
    } else {
      result.brokenRefs = validation.broken.slice(0, 20);
    }

    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
    };
  }
}

// =============================================================================
// AUTODOC STATUS
// =============================================================================

export class AutoDocStatusToolHandler extends BaseToolHandler<z.infer<typeof AutoDocStatusSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocStatusSchema.parse(args);
  }

  protected async execute(_args: z.infer<typeof AutoDocStatusSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    const status = await adm.getStatus();

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              status,
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC SYNC
// =============================================================================

export class AutoDocSyncToolHandler extends BaseToolHandler<z.infer<typeof AutoDocSyncSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocSyncSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocSyncSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    const { syncBidirectional, syncDbToDisk, syncDiskToDb } = await import(
      "../../autodoc/sync/file-sync.js"
    );

    const syncResult: {
      validated: number;
      brokenRefs: number;
      outdatedDocs: number;
      markedOutdated: string[];
      fileSync?: any;
    } = {
      validated: 0,
      brokenRefs: 0,
      outdatedDocs: 0,
      markedOutdated: [],
    };

    // Bidirectional file sync (if docsDir provided)
    if (args.docsDir) {
      const normalizedDocsDir = this.context.normalizeInputPath(args.docsDir) || args.docsDir;

      if (args.direction === "disk-to-db") {
        const diskToDb = await syncDiskToDb(
          normalizedDocsDir,
          async (fp: string) => adm.getDocumentsByFile(fp),
          async (fp: string, content: string) => adm.saveDocument(fp, content),
          8,
        );
        syncResult.fileSync = { diskToDb, dbToDisk: { written: [], errors: [] } };
      } else if (args.direction === "db-to-disk") {
        const dbToDisk = await syncDbToDisk(async () => adm.getAllDocuments(), 8);
        syncResult.fileSync = { diskToDb: { added: [], updated: [], errors: [] }, dbToDisk };
      } else {
        syncResult.fileSync = await syncBidirectional(
          normalizedDocsDir,
          async (fp: string) => adm.getDocumentsByFile(fp),
          async () => adm.getAllDocuments(),
          async (fp: string, content: string) => adm.saveDocument(fp, content),
          8,
        );
      }
    }

    // Validate all references
    const validation = await adm.validateReferences();
    syncResult.validated = validation.total;
    syncResult.brokenRefs = validation.broken.length;

    // Get and report outdated docs
    const outdated = await adm.getOutdatedDocs();
    syncResult.outdatedDocs = outdated.length;

    // If scope is "file", only process that file
    if (args.scope === "file" && args.filePath) {
      const normalizedPath = this.context.normalizeInputPath(args.filePath) || args.filePath;
      const fileDocs = await adm.getDocumentsByFile(normalizedPath);
      for (const doc of fileDocs) {
        if (doc.confidence < 0.7) {
          syncResult.markedOutdated.push(doc.id);
        }
      }
    } else {
      syncResult.markedOutdated = outdated.map((o: any) => o.docId);
    }

    // Build result message
    const fileSyncMsg = syncResult.fileSync
      ? ` Files: ${syncResult.fileSync.diskToDb.added.length} added, ${syncResult.fileSync.diskToDb.updated.length} updated, ${syncResult.fileSync.dbToDisk.written.length} written.`
      : "";

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              message: `Sync completed. ${syncResult.brokenRefs} broken refs, ${syncResult.outdatedDocs} outdated docs.${fileSyncMsg}`,
              ...syncResult,
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC GENERATE
// =============================================================================

export class AutoDocGenerateToolHandler extends BaseToolHandler<z.infer<typeof AutoDocGenerateSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocGenerateSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocGenerateSchema>): Promise<ToolResult> {
    const container = this.context.getServiceContainer?.();
    if (!container) {
      return autodocNotEnabledResult();
    }

    const nodePath = await import("node:path");
    const { execSync } = await import("node:child_process");
    const { writeDocumentToDisk } = await import("../../autodoc/sync/file-sync.js");

    // Use provided rootDir or current directory
    const targetDir = this.context.normalizeInputPath(args.rootDir || "") || process.cwd();

    // Find git repo root for .autodoc/ (falls back to targetDir)
    let repoRoot = targetDir;
    try {
      repoRoot = execSync("git rev-parse --show-toplevel", {
        cwd: targetDir,
        encoding: "utf-8",
        windowsHide: true,
        stdio: ["pipe", "pipe", "pipe"],
      }).trim();
    } catch {
      // Not a git repo, use targetDir
    }

    const targetAutodocDir = args.autodocDir
      ? this.context.normalizeInputPath(args.autodocDir) || args.autodocDir
      : nodePath.join(repoRoot, ".autodoc");

    // Detect language if auto
    let docLanguage: "auto" | "en" | "ru" | "zh" = args.language || "auto";
    if (docLanguage === "auto") {
      try {
        const adm = await container.getAutoDocManager();
        docLanguage = adm?.getConfig()?.language || "en";
      } catch {
        docLanguage = "en";
      }
    }

    // Import generator and general docs handler
    const { generateDocs } = await import("../../autodoc/generator/doc-generator.js");
    const { ensureGeneralDocs } = await import("../../autodoc/generator/general-docs.js");

    // Ensure .autodoc/ exists with template files (creates only if missing)
    ensureGeneralDocs(targetAutodocDir);

    // Generate module docs only (NOT .autodoc/ files - those are user-maintained)
    const result = await generateDocs({
      rootDir: targetDir,
      exclude: args.exclude,
      maxDepth: args.maxDepth,
    });

    // Filter by module name if specified
    if (args.module) {
      const filterLower = args.module.toLowerCase();
      result.modules = result.modules.filter(
        (m: any) => m.name.toLowerCase() === filterLower || m.name.toLowerCase().includes(filterLower),
      );
      result.files = result.files.filter((f: any) =>
        result.modules.some((m: any) => f.path.includes(m.path)),
      );
    }

    // Detect and use LLM if requested
    let llmStatus = "not_requested";
    if (args.useLlm && result.modules.length > 0) {
      const { detectLLMProviders, batchGenerateDocs } = await import("../../autodoc/llm/index.js");
      const { recommended } = await detectLLMProviders();

      if (recommended) {
        const modelName = (recommended as any).selectedModel || recommended.name;
        llmStatus = `using_${recommended.name}:${modelName}`;
        this.context.logger.info?.(
          "AUTODOC",
          `Using LLM: ${recommended.name} (${modelName}) for ${result.modules.length} module(s), lang=${docLanguage}`,
          {},
          this.context.requestId,
        );

        try {
          const enhancedDocs = await batchGenerateDocs(recommended, result.modules, {
            concurrency: 1,
            language: docLanguage,
            onProgress: (completed: number, total: number) => {
              this.context.logger.debug?.("AUTODOC", `LLM progress: ${completed}/${total}`, {}, this.context.requestId);
            },
          });

          for (const file of result.files) {
            const enhanced = enhancedDocs.get(file.path.replace(/AUTODOC\.md$/, "").replace(/[\\/]$/, ""));
            if (enhanced) {
              file.content = enhanced;
            }
          }
        } catch (error) {
          this.context.logger.warn?.(
            "AUTODOC",
            `LLM generation failed: ${(error as Error).message}`,
            {},
            this.context.requestId,
          );
          llmStatus = `error_${recommended.name}`;
        }
      } else {
        llmStatus = "no_provider_available";
        this.context.logger.warn?.(
          "AUTODOC",
          "No LLM provider available. Install Ollama or configure TGI/OpenAI.",
          {},
          this.context.requestId,
        );
      }
    }

    // If not preview, write files (with incremental update support)
    let filesWritten = 0;
    const incrementalChanges: Array<{ path: string; changes: string[] }> = [];

    if (!args.preview) {
      const adm = await container.getAutoDocManager();

      if (args.incremental) {
        const { updateModuleDoc } = await import("../../autodoc/generator/incremental-updater.js");

        for (const file of result.files) {
          try {
            const modulePath = file.path.replace(/[\\/]AUTODOC\.md$/, "");

            const updateResult = await updateModuleDoc(modulePath, file.path, file.content, {
              useLlm: args.useLlm,
            });

            if (updateResult.updated && updateResult.newContent) {
              if (adm) {
                await adm.saveDocument(file.path, updateResult.newContent, { autoGenerated: true });
              }
              await writeDocumentToDisk(file.path, updateResult.newContent);
              filesWritten++;

              incrementalChanges.push({
                path: file.path,
                changes: updateResult.changes.map((c: any) => c.description),
              });
            }
          } catch (error) {
            this.context.logger.warn?.(
              "AUTODOC",
              `Incremental update failed for ${file.path}: ${(error as Error).message}`,
              {},
              this.context.requestId,
            );
            // Fall back to full overwrite
            try {
              if (adm) {
                await adm.saveDocument(file.path, file.content, { autoGenerated: true });
              }
              await writeDocumentToDisk(file.path, file.content);
              filesWritten++;
            } catch (innerError) {
              this.context.logger.warn?.(
                "AUTODOC",
                `Failed to write ${file.path}: ${(innerError as Error).message}`,
                {},
                this.context.requestId,
              );
            }
          }
        }
      } else {
        // Full overwrite mode (incremental=false)
        for (const file of result.files) {
          try {
            if (adm) {
              await adm.saveDocument(file.path, file.content, { autoGenerated: true });
            }
            await writeDocumentToDisk(file.path, file.content);
            filesWritten++;
          } catch (error) {
            this.context.logger.warn?.(
              "AUTODOC",
              `Failed to write ${file.path}: ${(error as Error).message}`,
              {},
              this.context.requestId,
            );
          }
        }
      }
    }

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              preview: args.preview,
              useLlm: args.useLlm,
              llmStatus,
              incremental: args.incremental,
              language: docLanguage,
              modulesFound: result.modules.length,
              filesToGenerate: result.files.length,
              filesWritten,
              incrementalChanges: args.incremental ? incrementalChanges : undefined,
              modules: result.modules.map((m: any) => ({
                name: m.name,
                path: m.path,
                files: m.files.length,
                exports: m.exports.slice(0, 5),
              })),
              files: result.files.map((f: any) => ({
                path: f.path,
                type: f.type,
                preview: args.preview ? f.content.slice(0, 200) + "..." : undefined,
              })),
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC CHANGELOG
// =============================================================================

export class AutoDocChangelogToolHandler extends BaseToolHandler<z.infer<typeof AutoDocChangelogSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocChangelogSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocChangelogSchema>): Promise<ToolResult> {
    const adm = await getAutoDocManagerFromContext(this.context);
    if (!adm) {
      return autodocNotEnabledResult();
    }

    const changelog = await adm.getChangelog({
      since: args.since,
      limit: args.limit,
      branch: args.branch,
    });

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              entriesCount: changelog.length,
              entries: changelog.map((entry: any) => ({
                id: entry.id,
                timestamp: entry.timestamp,
                date: new Date(entry.timestamp).toISOString(),
                branch: entry.branch,
                summary: entry.summary,
                changesCount: entry.changes?.length || 0,
                impactedDocsCount: entry.impactedDocs?.length || 0,
              })),
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC INSTALL HOOKS
// =============================================================================

export class AutoDocInstallHooksToolHandler extends BaseToolHandler<z.infer<typeof AutoDocInstallHooksSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocInstallHooksSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocInstallHooksSchema>): Promise<ToolResult> {
    const container = this.context.getServiceContainer?.();
    if (!container) {
      return {
        content: [{ type: "text", text: JSON.stringify({ error: "ServiceContainer not available" }) }],
      };
    }

    const { installPreCommitHook, uninstallHooks, getHookStatus } = await import(
      "../../autodoc/hooks/hook-installer.js"
    );

    const projectPath = container.directory;

    if (args.action === "status") {
      const status = await getHookStatus(projectPath);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: true,
                gitRepo: status.gitRepo,
                hooksDir: status.hooksDir,
                preCommitInstalled: status.preCommit,
              },
              null,
              2,
            ),
          },
        ],
      };
    }

    if (args.action === "uninstall") {
      const result = await uninstallHooks(projectPath);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                success: result.success,
                removed: result.installed,
                skipped: result.skipped,
                errors: result.errors,
              },
              null,
              2,
            ),
          },
        ],
      };
    }

    // Default: install
    const result = await installPreCommitHook(projectPath);
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: result.success,
              installed: result.installed,
              skipped: result.skipped,
              errors: result.errors,
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}

// =============================================================================
// AUTODOC DETECT LANGUAGE
// =============================================================================

export class AutoDocDetectLanguageToolHandler extends BaseToolHandler<z.infer<typeof AutoDocDetectLanguageSchema>> {
  protected parseArgs(args: unknown) {
    return AutoDocDetectLanguageSchema.parse(args);
  }

  protected async execute(args: z.infer<typeof AutoDocDetectLanguageSchema>): Promise<ToolResult> {
    const { detectLanguageFromText, aggregateLanguageDetection } = await import(
      "../../autodoc/i18n/language-detector.js"
    );

    type DetectionResult = ReturnType<typeof detectLanguageFromText>;
    const results: DetectionResult[] = [];

    // Analyze code comments
    if (args.scope === "comments" || args.scope === "all") {
      const graphStorage = await this.context.getGraphStorage();
      const allEntities = await graphStorage.getAllEntities();
      const entities = allEntities.slice(0, args.sampleSize * 2);

      let analyzed = 0;
      for (const entity of entities) {
        if (analyzed >= args.sampleSize) break;
        if (entity.metadata?.["comments"]) {
          const commentsText = Array.isArray(entity.metadata["comments"])
            ? entity.metadata["comments"].join("\n")
            : String(entity.metadata["comments"]);
          const result = detectLanguageFromText(commentsText);
          if (result.confidence > 0) {
            results.push(result);
            analyzed++;
          }
        }
      }
    }

    // Analyze existing docs
    if (args.scope === "docs" || args.scope === "all") {
      const adm = await getAutoDocManagerFromContext(this.context);
      if (adm) {
        const allDocs = await adm.searchDocsByText("", args.sampleSize);

        for (const doc of allDocs) {
          const result = detectLanguageFromText(doc.content);
          if (result.confidence > 0) {
            results.push(result);
          }
        }
      }
    }

    // Aggregate results
    const aggregated = aggregateLanguageDetection(results);

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            {
              success: true,
              detectedLanguage: aggregated.language,
              confidence: Math.round(aggregated.confidence * 100) / 100,
              samplesAnalyzed: results.length,
              charCounts: aggregated.charCounts,
              recommendation:
                aggregated.confidence > 0.5
                  ? `Use language: ${aggregated.language}`
                  : "Low confidence - defaulting to 'en'",
            },
            null,
            2,
          ),
        },
      ],
    };
  }
}
