/**
 * TASK-001: Storage Type Definitions for Indexer Agent
 *
 * Type definitions for SQLite storage layer and graph operations.
 * Provides interfaces for entities, relationships, and storage operations.
 *
 * Architecture References:
 * - Agent Types: src/types/agent.ts
 * - Parser Types: src/types/parser.ts
 * - Base Agent: src/agents/base.ts
 */

import { CACHE_CONSTANTS, DATABASE_CONSTANTS } from "../config/constants.js";
import { log } from "../logging/index.js";
// =============================================================================
// 1. IMPORTS AND DEPENDENCIES
// =============================================================================
import type { ParsedEntity } from "./parser.js";
export type { ParsedEntity };

// =============================================================================
// 2. CONSTANTS AND CONFIGURATION
// =============================================================================
export const MAX_BATCH_SIZE = 1000;
export const DEFAULT_CACHE_TTL = CACHE_CONSTANTS.CACHE_TTL_MS;
export const MAX_CONNECTIONS = DATABASE_CONSTANTS.CONNECTION_POOL_SIZE;

// =============================================================================
// 3. DATA MODELS AND TYPE DEFINITIONS
// =============================================================================

/**
 * Entity types in the code graph
 */
export enum EntityType {
  FUNCTION = "function",
  CLASS = "class",
  METHOD = "method",
  INTERFACE = "interface",
  TYPE = "type",
  IMPORT = "import",
  EXPORT = "export",
  VARIABLE = "variable",
  CONSTANT = "constant",
  PACKAGE = "package",
  COMMENT = "comment",
}

/**
 * Relationship types between entities
 */
export enum RelationType {
  CALLS = "calls",
  IMPORTS = "imports",
  EXPORTS = "exports",
  EXTENDS = "extends",
  IMPLEMENTS = "implements",
  REFERENCES = "references",
  CONTAINS = "contains",
  DEPENDS_ON = "depends_on",
  DOCUMENTS = "documents", // Comment documents code entity

  // Reverse relationships for bidirectional tracing
  CALLED_BY = "called_by", // Reverse of CALLS: B called_by A when A calls B
  IMPORTED_BY = "imported_by", // Reverse of IMPORTS
  REFERENCED_BY = "referenced_by", // Reverse of REFERENCES
  EXTENDED_BY = "extended_by", // Reverse of EXTENDS
  IMPLEMENTED_BY = "implemented_by", // Reverse of IMPLEMENTS

  // NgRx/Redux state management relationships
  DISPATCHES_ACTION = "dispatches_action", // Component/Effect → Action
  LISTENS_TO_ACTION = "listens_to_action", // Effect → Action (ofType)
  HANDLES_ACTION = "handles_action", // Reducer → Action (on)
  SELECTS_STATE = "selects_state", // Component → Selector
  MODIFIES_STATE = "modifies_state", // Reducer → State slice
}

/**
 * Core entity stored in the graph (enhanced for v2)
 */
export interface Entity {
  id: string;
  name: string;
  type: EntityType;
  filePath: string;
  location: {
    start: { line: number; column: number; index: number };
    end: { line: number; column: number; index: number };
  };
  metadata: {
    modifiers?: string[];
    returnType?: string | undefined;
    parameters?: Array<{
      name: string;
      type?: string | undefined;
      optional?: boolean;
      defaultValue?: string | undefined;
    }>;
    importData?: {
      source: string;
      specifiers: Array<{ local: string; imported?: string }>;
      isDefault?: boolean;
      isNamespace?: boolean;
    };
    // Additional useful fields for all languages
    signature?: string | undefined;
    language?: string | undefined;
    decorators?: Array<{
      name: string;
      arguments?: string[];
      isBuiltin?: boolean;
    }>;
    [key: string]: unknown;
  };
  hash: string;
  createdAt: number;
  updatedAt: number;

  // Enhanced v2 fields
  complexityScore?: number | undefined;
  language?: string | undefined;
  sizeBytes?: number | undefined;

  // Embedding fields (generated by workers during parsing)
  embeddingBase64?: string;
  embeddingText?: string;
}

/**
 * Relationship between entities (enhanced for v2)
 */
export interface Relationship {
  id: string;
  fromId: string;
  toId: string;
  type: RelationType;
  metadata?: {
    line?: number | undefined;
    column?: number;
    context?: string;
    [key: string]: unknown;
  };

  // Enhanced v2 fields
  weight?: number;
  createdAt?: number;
}

/**
 * File tracking information
 */
export interface FileInfo {
  path: string;
  hash: string;
  lastIndexed: number;
  entityCount: number;
}

/**
 * Entity query parameters (used by findEntities)
 */
export interface EntityQuery {
  filters?: {
    entityType?: EntityType | EntityType[];
    filePath?: string | string[];
    name?: string | RegExp;
  };
  limit?: number;
  offset?: number;
}

/**
 * Relationship query parameters (used by findRelationships)
 */
export interface RelationshipQuery {
  filters?: {
    relationshipType?: RelationType | RelationType[];
    fromId?: string | string[];
    toId?: string | string[];
  };
  limit?: number;
  offset?: number;
}

/**
 * Graph query parameters (for executeQuery and subgraph operations)
 */
export interface GraphQuery {
  type: "entity" | "relationship" | "subgraph";
  filters?: {
    entityType?: EntityType | EntityType[];
    relationshipType?: RelationType | RelationType[];
    filePath?: string | string[];
    name?: string | RegExp;
  };
  depth?: number;
  limit?: number;
  offset?: number;
}

/**
 * Graph query result
 */
export interface GraphQueryResult {
  entities: Entity[];
  relationships: Relationship[];
  stats: {
    totalEntities: number;
    totalRelationships: number;
    queryTimeMs: number;
  };
}

/**
 * Entity change for incremental updates
 */
export interface EntityChange {
  type: "added" | "modified" | "deleted";
  entity?: Entity;
  entityId?: string | undefined;
  filePath: string;
  timestamp: number;
}

/**
 * Database schema definition
 */
export interface GraphSchema {
  entities: {
    id: string;
    name: string;
    type: string;
    file_path: string;
    location: string; // JSON string
    metadata: string; // JSON string
    hash: string;
    created_at: number;
    updated_at: number;
  };

  relationships: {
    id: string;
    from_id: string;
    to_id: string;
    type: string;
    metadata: string; // JSON string
  };

  files: {
    path: string;
    hash: string;
    last_indexed: number;
    entity_count: number;
  };
}

/**
 * Storage metrics (enhanced for v2)
 */
export interface StorageMetrics {
  totalEntities: number;
  totalRelationships: number;
  totalFiles: number;
  databaseSizeMB: number;
  indexSizeMB: number;
  cacheHitRate: number;
  averageQueryTimeMs: number;
  lastVacuum: number;

  // Enhanced v2 metrics
  totalEmbeddings?: number;
  vectorSearchEnabled?: boolean;
  performanceMetricsCount?: number;
  memoryUsageMB?: number;
  concurrentConnections?: number;
}

/**
 * Batch operation result
 */
export interface BatchResult {
  processed: number;
  failed: number;
  errors: Array<{
    item: unknown;
    error: string;
  }>;
  timeMs: number;
}

/**
 * Cache entry for query results
 */
export interface CacheEntry<T = unknown> {
  key: string;
  value: T;
  timestamp: number;
  ttl: number;
  hits: number;
  size: number;
}

/**
 * Connection pool statistics
 */
export interface PoolStats {
  total: number;
  active: number;
  idle: number;
  waiting: number;
  timeouts: number;
}

// =============================================================================
// 4. STORAGE INTERFACE DEFINITIONS
// =============================================================================

/**
 * Main storage interface for graph operations
 */
export interface GraphStorage {
  // Entity operations
  insertEntity(entity: Entity): Promise<void>;
  insertEntities(entities: Entity[]): Promise<BatchResult>;
  updateEntity(id: string, updates: Partial<Entity>): Promise<void>;
  deleteEntity(id: string): Promise<void>;
  getEntity(id: string): Promise<Entity | null>;
  findEntities(query: EntityQuery): Promise<Entity[]>;

  // NEW: Enhanced entity queries for Chaos Analysis and advanced tools
  getAllEntities(): Promise<Entity[]>;
  searchEntities(options: {
    namePattern?: string | undefined;
    types?: EntityType[] | undefined;
    filePath?: string;
    limit?: number;
  }): Promise<Entity[]>;

  /** Count entities grouped by language (efficient SQL aggregation for TechnologyDetector) */
  countByLanguage(): Promise<Map<string, { count: number; fileCount: number }>>;

  // Relationship operations
  insertRelationship(relationship: Relationship): Promise<void>;
  insertRelationships(relationships: Relationship[]): Promise<BatchResult>;
  deleteRelationship(id: string): Promise<void>;
  getRelationshipsForEntity(entityId: string, type?: RelationType): Promise<Relationship[]>;
  findRelationships(query: RelationshipQuery): Promise<Relationship[]>;

  /** Get ALL relationships efficiently (single query, no batching) */
  getAllRelationships(): Promise<Relationship[]>;

  // NEW: Alias for convenience (used by Chaos Analysis)
  getRelationships(sourceId: string, type?: RelationType): Promise<Relationship[]>;

  /** Find incoming relationships by entity name (for NgRx flow tracing) */
  findIncomingRelationshipsByName(entityName: string, types?: RelationType[]): Promise<Relationship[]>;

  // File operations
  updateFileInfo(info: FileInfo): Promise<void>;
  getFileInfo(path: string): Promise<FileInfo | null>;
  getOutdatedFiles(since: number): Promise<FileInfo[]>;
  /** Get all indexed files with their lastIndexed timestamps */
  getAllIndexedFiles(): Promise<Map<string, number>>;
  /** Delete file info by path */
  deleteFileInfo(path: string): Promise<void>;

  // Entity operations by file path (for incremental indexing)
  /** Get entity IDs by file path (for FAISS cleanup) */
  getEntityIdsByFilePath(filePath: string): Promise<string[]>;
  /** Delete all entities for a file path, returns deleted IDs */
  deleteEntitiesByFilePath(filePath: string): Promise<string[]>;

  // Query operations
  executeQuery(query: GraphQuery): Promise<GraphQueryResult>;
  getSubgraph(entityId: string, depth: number): Promise<GraphQueryResult>;

  // Maintenance operations
  vacuum(): Promise<void>;
  analyze(): Promise<void>;
  getMetrics(): Promise<StorageMetrics>;

  // Project context (v4: unified libsql storage)
  setProject(projectPath: string, branchName?: string): void;
  clear(): Promise<void>;
  getStatistics(): Promise<{ totalEntities: number; totalRelationships: number; totalFiles: number }>;
}

/**
 * Cache manager interface
 */
export interface CacheManager {
  get<T>(key: string): T | null;
  set<T>(key: string, value: T, ttl?: number): void;
  delete(key: string): void;
  clear(): void;
  getStats(): {
    size: number;
    hits: number;
    misses: number;
    hitRate: number;
  };
}

/**
 * Connection pool interface
 */
export interface ConnectionPool<T> {
  acquire(): Promise<T>;
  release(connection: T): void;
  destroy(connection: T): void;
  drain(): Promise<void>;
  getStats(): PoolStats;
}

// =============================================================================
// 5. ENHANCED V2 TYPES
// =============================================================================

/**
 * Performance metrics entry
 */
export interface PerformanceMetric {
  id: string;
  operation: string;
  durationMs: number;
  entityCount?: number;
  memoryUsage?: number;
  createdAt: number;
}

/**
 * Vector embedding for semantic search
 */
export interface VectorEmbedding {
  id: string;
  entityId: string;
  content: string;
  vectorData?: ArrayBuffer | null;
  modelName: string;
  createdAt: number;
}

/**
 * Enhanced cache entry with v2 features
 */
export interface EnhancedCacheEntry<T = unknown> extends CacheEntry<T> {
  missCount?: number;
  lastAccessed?: number;
}

// =============================================================================
// 6. HELPER TYPES
// =============================================================================

/**
 * Convert ParsedEntity to Entity
 */
export function parsedEntityToEntity(
  parsed: ParsedEntity,
  filePath: string,
  hash: string,
): Omit<Entity, "id" | "createdAt" | "updatedAt"> {
  return {
    name: parsed.name,
    type: parsed.type as EntityType,
    filePath,
    location: parsed.location,
    metadata: {
      modifiers: parsed.modifiers,
      returnType: parsed.returnType,
      parameters: parsed.parameters,
      importData: parsed.importData,
      signature: parsed.signature,
      language: parsed.language,
      decorators: parsed.decorators,
      // Complexity metrics from ts-complexity-analyzer
      metrics: parsed.complexity
        ? {
            cyclomaticComplexity: parsed.complexity.cyclomatic,
            cognitiveComplexity: parsed.complexity.cognitive,
            linesOfCode: parsed.complexity.linesOfCode,
            linesOfLogic: parsed.complexity.linesOfLogic,
            nestingDepth: parsed.complexity.nestingDepth,
            parameterCount: parsed.complexity.parameterCount,
            returnCount: parsed.complexity.returnCount,
          }
        : undefined,
    },
    hash,
    // Language field for technology detection
    language: parsed.language,
    // Embedding fields (generated by workers during parsing)
    embeddingBase64: parsed.embeddingBase64,
    embeddingText: parsed.embeddingText,
  };
}

/**
 * Flatten ParsedEntity tree - extracts all children recursively into flat array
 * This is critical for storing class members (properties, methods) as separate entities
 */
export function flattenParsedEntities(entities: ParsedEntity[]): ParsedEntity[] {
  const result: ParsedEntity[] = [];
  let childrenCount = 0;

  function flatten(entity: ParsedEntity, parentName?: string, parentFilePath?: string): void {
    // Add the entity itself
    result.push(entity);

    // Recursively flatten children
    if (entity.children && entity.children.length > 0) {
      for (const child of entity.children) {
        childrenCount++;

        // Determine qualified name for child
        // Some parsers (like K2) already qualify child names, so avoid double-qualifying
        const parentPrefix = parentName || entity.name;
        const expectedPrefix = `${parentPrefix}.`;
        const alreadyQualified = child.name.startsWith(expectedPrefix);
        const qualifiedName = alreadyQualified ? child.name : `${parentPrefix}.${child.name}`;

        // Inherit filePath and language from parent if child doesn't have them
        const qualifiedChild: ParsedEntity = {
          ...child,
          name: qualifiedName,
          filePath: child.filePath || parentFilePath || entity.filePath,
          language: child.language || entity.language,
        };
        flatten(qualifiedChild, qualifiedChild.name, qualifiedChild.filePath);
      }
    }
  }

  for (const entity of entities) {
    flatten(entity, undefined, entity.filePath);
  }

  if (childrenCount > 0) {
    log.d("STORAGE", "flatten_children", { children: childrenCount, topLevel: entities.length });
  }

  return result;
}

/**
 * Type guard for Entity
 */
export function isEntity(obj: unknown): obj is Entity {
  return typeof obj === "object" && obj !== null && "id" in obj && "name" in obj && "type" in obj && "filePath" in obj;
}

/**
 * Type guard for Relationship
 */
export function isRelationship(obj: unknown): obj is Relationship {
  return typeof obj === "object" && obj !== null && "id" in obj && "fromId" in obj && "toId" in obj && "type" in obj;
}
