/**
 * Protobuf Code Linker
 *
 * Analyzes relationships between protobuf service definitions and source code.
 * Detects gRPC server implementations (producers), client stubs (consumers),
 * and generated types.
 *
 * Follows the pattern from swagger-code-linker.ts.
 */

import type { Entity } from "../../types/storage.js";
import { RelationType } from "../../types/storage.js";
import type { ProtobufAnalysis, ProtobufCodeLink, ProtobufRelationship } from "./types.js";

// =============================================================================
// CONSTANTS
// =============================================================================

/** Suffixes commonly added to generated protobuf types */
const TYPE_SUFFIXES = ["Pb", "Proto", "Message", "Request", "Response", "Dto", "DTO", "Model"];

/** Patterns for detecting generated protobuf files */
const GENERATED_FILE_PATTERNS = [
  /_pb2\.py$/,
  /_pb2_grpc\.py$/,
  /\.pb\.go$/,
  /_grpc\.pb\.go$/,
  /Grpc\.cs$/,
  /\.g\.cs$/,
  /_pb\.ts$/,
  /_pb\.js$/,
  /_pb\.d\.ts$/,
  /\.pb\.cc$/,
  /\.pb\.h$/,
  /\.grpc\.pb\.cc$/,
  /\.grpc\.pb\.h$/,
];

/** Markers found in generated protobuf files */
const GENERATED_MARKERS = [
  "Code generated by protoc-gen-go",
  "Generated by the protocol buffer compiler",
  "source: ",
  "@javax.annotation.Generated",
  "Generated by the gRPC",
  "protoc-gen-grpc",
  "DO NOT EDIT",
  "auto-generated",
  "buf:lint:ignore",
];

/** Producer patterns for gRPC server implementations */
const PRODUCER_PATTERNS = [
  // Go
  { pattern: /pb\.Register(\w+)Server/i, framework: "go-grpc", extract: 1 },
  { pattern: /Unimplemented(\w+)Server/i, framework: "go-grpc", extract: 1 },
  { pattern: /Must[eE]mbed[Uu]nimplemented(\w+)Server/i, framework: "go-grpc", extract: 1 },
  // Java/Kotlin
  { pattern: /extends\s+(\w+)Grpc\.(\w+)ImplBase/i, framework: "java-grpc", extract: 1 },
  { pattern: /@GrpcService/i, framework: "java-grpc", extract: null },
  // C#/.NET
  { pattern: /:\s*(\w+)\.(\w+)Base\b/i, framework: "dotnet-grpc", extract: 1 },
  { pattern: /\[GrpcService\]/i, framework: "dotnet-grpc", extract: null },
  // Python
  { pattern: /add_(\w+)Servicer_to_server/i, framework: "python-grpc", extract: 1 },
  { pattern: /(\w+)Servicer\b/i, framework: "python-grpc", extract: 1 },
  // Node.js
  { pattern: /addService\s*\(\s*(\w+)\.service/i, framework: "node-grpc", extract: 1 },
  { pattern: /@grpc\/grpc-js/i, framework: "node-grpc", extract: null },
];

/** Consumer patterns for gRPC clients */
const CONSUMER_PATTERNS = [
  // Go
  { pattern: /New(\w+)Client\s*\(/i, framework: "go-grpc", extract: 1 },
  // Java
  { pattern: /(\w+)Grpc\.new\w+Stub/i, framework: "java-grpc", extract: 1 },
  // C#
  { pattern: /new\s+(\w+)\.(\w+)Client\s*\(/i, framework: "dotnet-grpc", extract: 1 },
  // Python
  { pattern: /(\w+)Stub\s*\(/i, framework: "python-grpc", extract: 1 },
  // Node.js
  { pattern: /new\s+\w+\.(\w+)Client\s*\(/i, framework: "node-grpc", extract: 1 },
];

/** Codegen configuration files for protobuf */
const CODEGEN_CONFIGS = ["buf.gen.yaml", "buf.yaml", "buf.lock", "buf.work.yaml", "grpc_tools_node_protoc"];

// =============================================================================
// MAIN ANALYSIS
// =============================================================================

/**
 * Analyze links between protobuf definitions and source code
 */
export function analyzeProtobufCodeLinks(allEntities: Entity[]): ProtobufAnalysis {
  // Separate proto entities from code entities
  const protoEntities = allEntities.filter((e) => e.metadata?.["protoType"]);
  const codeEntities = allEntities.filter((e) => !e.metadata?.["protoType"] && !e.metadata?.["swaggerType"]);

  if (protoEntities.length === 0) {
    return {
      producers: [],
      consumers: [],
      generatedTypes: [],
      generatedFileMarkers: [],
      codegenConfigs: [],
    };
  }

  // Extract proto services for matching
  const protoServices = protoEntities.filter((e) => e.metadata?.["protoType"] === "service");
  const protoMessages = protoEntities.filter((e) => e.metadata?.["protoType"] === "message");

  // Detect producers (gRPC server implementations)
  const producers = detectProducers(protoServices, codeEntities);

  // Detect consumers (gRPC client stubs)
  const consumers = detectConsumers(protoServices, codeEntities);

  // Match generated types
  const generatedTypes = matchProtoTypesToCode(protoMessages, codeEntities);

  // Find generated file markers
  const generatedFileMarkers = findGeneratedMarkers(codeEntities);

  // Find codegen configs
  const codegenConfigs = findCodegenConfigs(allEntities);

  return {
    producers,
    consumers,
    generatedTypes,
    generatedFileMarkers,
    codegenConfigs,
  };
}

/**
 * Build relationships for graph storage
 */
export function buildProtobufRelationships(analysis: ProtobufAnalysis): ProtobufRelationship[] {
  const relationships: ProtobufRelationship[] = [];

  for (const link of analysis.producers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.protoEntityName,
      type: RelationType.PRODUCES_API,
      fromFile: link.codeFilePath,
      toFile: link.protoFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        serviceName: link.protoEntityName,
        context: "gRPC server implementation",
      },
    });
  }

  for (const link of analysis.consumers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.protoEntityName,
      type: RelationType.CONSUMES_API,
      fromFile: link.codeFilePath,
      toFile: link.protoFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        serviceName: link.protoEntityName,
        context: "gRPC client stub",
      },
    });
  }

  for (const link of analysis.generatedTypes) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.protoEntityName,
      type: RelationType.GENERATED_FROM,
      fromFile: link.codeFilePath,
      toFile: link.protoFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        messageType: link.protoEntityName,
        context: "generated from proto message",
      },
    });
  }

  return relationships;
}

// =============================================================================
// PRODUCER DETECTION
// =============================================================================

function detectProducers(protoServices: Entity[], codeEntities: Entity[]): ProtobufCodeLink[] {
  const links: ProtobufCodeLink[] = [];

  for (const service of protoServices) {
    const serviceName = service.name;

    for (const code of codeEntities) {
      const codeText = (code.metadata?.signature as string) ?? code.name;
      const evidence: string[] = [];
      let confidence = 0;

      for (const pattern of PRODUCER_PATTERNS) {
        const match = pattern.pattern.exec(codeText);
        if (match) {
          const extractedName = pattern.extract !== null ? match[pattern.extract]! : "";
          if (pattern.extract === null || nameMatches(extractedName, serviceName)) {
            evidence.push(`${pattern.framework}: matched pattern ${pattern.pattern.source}`);
            confidence = Math.max(confidence, 0.7);
          }
        }
      }

      // Check class name similarity
      if (confidence === 0) {
        const nameScore = computeNameSimilarity(code.name, serviceName);
        if (nameScore >= 0.6) {
          // Also check if the code entity looks like a service implementation
          if (
            code.type === "class" &&
            (code.name.includes("Service") ||
              code.name.includes("Handler") ||
              code.name.includes("Impl") ||
              code.name.includes("Server"))
          ) {
            evidence.push(`Name similarity: ${code.name} ~ ${serviceName} (score: ${nameScore.toFixed(2)})`);
            confidence = nameScore * 0.6;
          }
        }
      }

      if (confidence > 0.3) {
        links.push({
          protoEntityName: serviceName,
          codeEntityName: code.name,
          codeFilePath: code.filePath,
          protoFilePath: service.filePath,
          linkType: "produces_api",
          confidence: Math.min(confidence, 1),
          evidence,
        });
      }
    }
  }

  return links;
}

// =============================================================================
// CONSUMER DETECTION
// =============================================================================

function detectConsumers(protoServices: Entity[], codeEntities: Entity[]): ProtobufCodeLink[] {
  const links: ProtobufCodeLink[] = [];

  for (const service of protoServices) {
    const serviceName = service.name;

    for (const code of codeEntities) {
      const codeText = (code.metadata?.signature as string) ?? code.name;
      const evidence: string[] = [];
      let confidence = 0;

      // Check generated file patterns
      const isGenerated = GENERATED_FILE_PATTERNS.some((pat) => pat.test(code.filePath));
      if (isGenerated) {
        evidence.push(`Generated file: ${code.filePath}`);
        confidence = Math.max(confidence, 0.5);
      }

      // Check consumer patterns
      for (const pattern of CONSUMER_PATTERNS) {
        const match = pattern.pattern.exec(codeText);
        if (match) {
          const extractedName = pattern.extract !== null ? match[pattern.extract]! : "";
          if (pattern.extract === null || nameMatches(extractedName, serviceName)) {
            evidence.push(`${pattern.framework}: matched pattern ${pattern.pattern.source}`);
            confidence = Math.max(confidence, 0.7);
          }
        }
      }

      if (confidence > 0.3) {
        links.push({
          protoEntityName: serviceName,
          codeEntityName: code.name,
          codeFilePath: code.filePath,
          protoFilePath: service.filePath,
          linkType: "consumes_api",
          confidence: Math.min(confidence, 1),
          evidence,
        });
      }
    }
  }

  return links;
}

// =============================================================================
// TYPE MATCHING
// =============================================================================

function matchProtoTypesToCode(protoMessages: Entity[], codeEntities: Entity[]): ProtobufCodeLink[] {
  const links: ProtobufCodeLink[] = [];

  // Build a set of code types for matching
  const codeTypes = codeEntities.filter((e) => e.type === "type" || e.type === "class" || e.type === "interface");

  for (const message of protoMessages) {
    const messageName = message.name;
    const strippedProto = stripTypeSuffix(messageName);

    for (const code of codeTypes) {
      const strippedCode = stripTypeSuffix(code.name);
      const evidence: string[] = [];
      let confidence = 0;

      // Check generated file
      const isGenerated = GENERATED_FILE_PATTERNS.some((pat) => pat.test(code.filePath));

      // Exact name match
      if (code.name === messageName || strippedCode === strippedProto) {
        confidence = isGenerated ? 0.9 : 0.6;
        evidence.push(`Name match: ${code.name} = ${messageName}`);
      }
      // Name with proto suffixes
      else if (
        code.name === `${messageName}Pb` ||
        code.name === `${messageName}Proto` ||
        code.name === `${messageName}Message` ||
        code.name === `I${messageName}` // Interface prefix
      ) {
        confidence = isGenerated ? 0.85 : 0.55;
        evidence.push(`Name match with suffix: ${code.name} ~ ${messageName}`);
      }

      if (isGenerated && confidence > 0) {
        evidence.push(`In generated file: ${code.filePath}`);
      }

      // Check field similarity for higher confidence
      if (confidence > 0.4) {
        const protoFields = (message.metadata?.["fields"] as Array<{ name: string }>) ?? [];
        const codeMembers = code.metadata?.["members"] as Array<{ name: string }> | undefined;
        if (codeMembers && protoFields.length > 0) {
          const protoFieldNames = new Set(protoFields.map((f) => f.name.toLowerCase()));
          const matching = codeMembers.filter((m) => protoFieldNames.has(m.name.toLowerCase()));
          if (matching.length > 0) {
            const overlap = matching.length / Math.max(protoFields.length, codeMembers.length);
            confidence = Math.min(1, confidence + overlap * 0.2);
            evidence.push(`${matching.length}/${protoFields.length} fields match`);
          }
        }
      }

      if (confidence > 0.3) {
        links.push({
          protoEntityName: messageName,
          codeEntityName: code.name,
          codeFilePath: code.filePath,
          protoFilePath: message.filePath,
          linkType: "generated_from",
          confidence: Math.min(confidence, 1),
          evidence,
        });
      }
    }
  }

  return links;
}

// =============================================================================
// GENERATED MARKERS & CODEGEN CONFIGS
// =============================================================================

function findGeneratedMarkers(codeEntities: Entity[]): string[] {
  const markers: string[] = [];

  for (const entity of codeEntities) {
    if (GENERATED_FILE_PATTERNS.some((pat) => pat.test(entity.filePath))) {
      markers.push(entity.filePath);
    }
  }

  return [...new Set(markers)];
}

function findCodegenConfigs(allEntities: Entity[]): string[] {
  const found: string[] = [];

  for (const entity of allEntities) {
    const name = entity.name.toLowerCase();
    const filePath = entity.filePath.toLowerCase();
    if (CODEGEN_CONFIGS.some((cfg) => name === cfg || filePath.endsWith(`/${cfg}`))) {
      found.push(entity.filePath);
    }
  }

  return [...new Set(found)];
}

/** Exported for integration with indexing pipeline */
export function getProtobufCodegenConfigFiles(): string[] {
  return [...CODEGEN_CONFIGS];
}

/** Exported for integration with indexing pipeline */
export function getProtobufGeneratedCodeMarkers(): string[] {
  return [...GENERATED_MARKERS];
}

// =============================================================================
// UTILITIES
// =============================================================================

function stripTypeSuffix(name: string): string {
  let result = name;
  for (const suffix of TYPE_SUFFIXES) {
    if (result.endsWith(suffix) && result.length > suffix.length) {
      result = result.slice(0, -suffix.length);
      break;
    }
  }
  return result;
}

function nameMatches(extracted: string, serviceName: string): boolean {
  if (!extracted) return false;
  const lower = extracted.toLowerCase();
  const serviceNameLower = serviceName.toLowerCase();
  return (
    lower === serviceNameLower ||
    serviceNameLower.includes(lower) ||
    lower.includes(serviceNameLower) ||
    serviceNameLower.replace(/service$/i, "") === lower.replace(/service$/i, "")
  );
}

function computeNameSimilarity(a: string, b: string): number {
  const aLower = a.toLowerCase().replace(/service|server|impl|handler|controller/gi, "");
  const bLower = b.toLowerCase().replace(/service|server|impl|handler|controller/gi, "");
  if (aLower === bLower) return 1.0;
  if (aLower.includes(bLower) || bLower.includes(aLower)) return 0.8;
  // Simple character overlap
  const aChars = new Set(aLower);
  const bChars = new Set(bLower);
  let overlap = 0;
  for (const c of aChars) if (bChars.has(c)) overlap++;
  return overlap / Math.max(aChars.size, bChars.size);
}
