/**
 * AutoDoc Tool Schemas
 * Schemas for automatic documentation generation and management
 */

import { z } from "zod";

export const AutoDocInitSchema = z.object({
  enabled: z.boolean().optional().default(true).describe("Enable AutoDoc functionality"),
  language: z.enum(["en", "ru"]).optional().default("en").describe("Documentation language"),
  docsDir: z.string().optional().describe("Directory for documentation files"),
});

export const AutoDocSaveSchema = z.object({
  filePath: z.string().describe("Path to the markdown documentation file"),
  content: z.string().describe("Markdown content to save"),
  type: z
    .enum(["entity_doc", "architecture", "flow", "process", "dependency", "deployment", "glossary", "module_index"])
    .optional()
    .describe("Document type"),
  autoGenerated: z.boolean().optional().default(true).describe("Mark as auto-generated"),
});

export const AutoDocGetSchema = z.object({
  docId: z.string().optional().describe("Document ID to retrieve"),
  filePath: z.string().optional().describe("File path to retrieve documents for"),
});

export const AutoDocSearchSchema = z.object({
  query: z.string().describe("Search query for documentation"),
  limit: z.number().optional().default(10).describe("Maximum results to return"),
  mode: z
    .enum(["text", "semantic", "hybrid"])
    .optional()
    .default("text")
    .describe("Search mode: text (keyword), semantic (vector similarity), hybrid (both)"),
});

export const AutoDocValidateSchema = z.object({
  filePath: z.string().optional().describe("Validate references in a specific file"),
  fixBroken: z.boolean().optional().default(false).describe("Attempt to fix broken references"),
});

export const AutoDocStatusSchema = z.object({});

export const AutoDocSyncSchema = z.object({
  scope: z
    .enum(["all", "outdated", "file"])
    .optional()
    .default("outdated")
    .describe("Sync scope: all docs, only outdated, or specific file"),
  filePath: z.string().optional().describe("File path when scope is 'file'"),
  docsDir: z.string().optional().describe("Documentation directory for bidirectional sync"),
  direction: z
    .enum(["both", "disk-to-db", "db-to-disk"])
    .optional()
    .default("both")
    .describe("Sync direction: both (bidirectional), disk-to-db, or db-to-disk"),
});

export const AutoDocGenerateSchema = z.object({
  rootDir: z.string().optional().describe("Root directory to scan (default: current indexed directory)"),
  autodocDir: z.string().optional().describe("Output directory for general docs (default: .autodoc)"),
  preview: z.boolean().optional().default(true).describe("Preview mode - show what would be generated without writing"),
  exclude: z.array(z.string()).optional().describe("Patterns to exclude from scanning"),
  maxDepth: z.number().optional().default(4).describe("Max depth to scan for modules"),
  useLlm: z
    .boolean()
    .optional()
    .default(false)
    .describe("Use LLM to generate meaningful documentation (requires Ollama/TGI/OpenAI)"),
  incremental: z
    .boolean()
    .optional()
    .default(true)
    .describe(
      "Incremental mode: only update changed parts, preserve existing content, mark deleted items. Set to false to regenerate from scratch.",
    ),
  module: z
    .string()
    .optional()
    .describe("Generate docs for a single module by name (e.g., 'utils', 'parsers'). Faster for testing LLM."),
  language: z
    .enum(["auto", "en", "ru", "zh"])
    .optional()
    .default("auto")
    .describe("Documentation language: 'auto' (detect from comments), 'en', 'ru', 'zh'"),
});

export const AutoDocChangelogSchema = z.object({
  since: z.number().optional().describe("Unix timestamp to filter changes since"),
  limit: z.number().optional().default(20).describe("Maximum entries to return"),
  branch: z.string().optional().describe("Filter by git branch"),
});

export const AutoDocInstallHooksSchema = z.object({
  action: z
    .enum(["install", "uninstall", "status"])
    .optional()
    .default("install")
    .describe("Action: install, uninstall, or check status"),
});

export const AutoDocDetectLanguageSchema = z.object({
  scope: z
    .enum(["comments", "docs", "all"])
    .optional()
    .default("all")
    .describe("Scope: analyze code comments, existing docs, or both"),
  sampleSize: z.number().optional().default(20).describe("Number of files to sample for detection"),
});
