/**
 * GraphQL Usage Detector
 *
 * Detects actively used GraphQL schema files via multi-signal scoring.
 * Delegates to base-usage-detector with GraphQL-specific config.
 */

import type { GraphStorage } from "../types/storage.js";
import {
  applyUsageMetadata,
  detectUsage,
  type FileUsage,
  type UsageResult,
  type UsageSignal,
} from "./base-usage-detector.js";

// Backward-compatible type aliases
export type GraphQLUsageResult = UsageResult;
export type GraphQLFileUsage = FileUsage;
export type GraphQLUsageSignal = UsageSignal;

export async function detectGraphQLUsage(storage: GraphStorage): Promise<UsageResult> {
  return detectUsage(storage, {
    logTag: "GRAPHQL_USAGE",
    entityFilter: (e) =>
      e.metadata?.["graphqlType"] === "schema" ||
      e.metadata?.["graphqlType"] === "query" ||
      e.metadata?.["graphqlType"] === "mutation",
    importPathMatcher: (toId) =>
      toId.includes("/generated/") ||
      toId.includes("/__generated__/") ||
      toId.includes(".generated.") ||
      toId.includes("/graphql/"),
    codegenKeywords: ["graphql-codegen", "apollo codegen", "graphql-code-generator", "gql-gen"],
    configFileNames: [
      "codegen.yml",
      "codegen.yaml",
      "codegen.ts",
      "codegen.js",
      ".graphqlrc.yml",
      ".graphqlrc.yaml",
      ".graphqlrc.json",
      ".graphqlrc.js",
      ".graphqlrc.ts",
      "apollo.config.js",
      "apollo.config.ts",
      "graphql.config.js",
      "graphql.config.ts",
      "graphql.config.yml",
      "graphql.config.yaml",
    ],
    generatedFilter: (e) =>
      !!e.metadata?.["isGenerated"] ||
      !!e.metadata?.["autoGenerated"] ||
      e.filePath.includes(".generated.") ||
      (e.filePath.includes("/generated/") && (e.filePath.endsWith(".ts") || e.filePath.endsWith(".tsx"))),
  });
}

export async function applyGraphQLUsageMetadata(storage: GraphStorage, usage: UsageResult): Promise<number> {
  return applyUsageMetadata(storage, usage);
}
