/**
 * Swagger Usage Detector
 *
 * Detects actively used swagger/OpenAPI files via multi-signal scoring.
 * Delegates to base-usage-detector with Swagger-specific config.
 */

import type { GraphStorage } from "../types/storage.js";
import { applyUsageMetadata, detectUsage, type FileUsage, type UsageResult } from "./base-usage-detector.js";

// Backward-compatible type aliases
export type SwaggerUsageResult = UsageResult;
export type SwaggerFileUsage = FileUsage;
export type { UsageSignal } from "./base-usage-detector.js";

export async function detectSwaggerUsage(storage: GraphStorage): Promise<UsageResult> {
  return detectUsage(storage, {
    logTag: "SWAGGER_USAGE",
    entityFilter: (e) => e.metadata?.["swaggerType"] === "api_spec",
    importPathMatcher: (toId) =>
      toId.includes("/generated/") ||
      toId.includes("/gen/") ||
      toId.includes("/__generated__/") ||
      toId.includes("/api-client/") ||
      toId.includes("/api/"),
    codegenKeywords: [
      "openapi-generator",
      "nswag",
      "autorest",
      "refitter",
      "ng-openapi-gen",
      "swagger-codegen",
      "generate-api",
      "generate-client",
    ],
    configFileNames: [
      "openapitools.json",
      "nswag.json",
      ".refitter",
      "ng-openapi-gen.json",
      "autorest.md",
      "swagger-codegen-config.json",
    ],
    generatedFilter: (e) =>
      !!e.metadata?.["isGenerated"] ||
      !!e.metadata?.["autoGenerated"] ||
      (!!e.filePath &&
        (e.filePath.includes("/generated/") || e.filePath.includes("/gen/") || e.filePath.includes("/__generated__/"))),
  });
}

export async function applySwaggerUsageMetadata(storage: GraphStorage, usage: UsageResult): Promise<number> {
  return applyUsageMetadata(storage, usage);
}
