/**
 * GraphQL Code Linker
 *
 * Analyzes relationships between GraphQL schema definitions and source code.
 * Detects resolver implementations, generated hooks/queries (consumers),
 * and generated types.
 *
 * Follows the pattern from swagger-code-linker.ts.
 */

import type { Entity } from "../../types/storage.js";
import { RelationType } from "../../types/storage.js";
import type { GraphQLAnalysis, GraphQLCodeLink, GraphQLRelationship } from "./types.js";

// =============================================================================
// CONSTANTS
// =============================================================================

/** Suffixes commonly added to generated GraphQL types */
const TYPE_SUFFIXES = [
  "Fragment",
  "Query",
  "Mutation",
  "Subscription",
  "Args",
  "Input",
  "Output",
  "Dto",
  "DTO",
  "Model",
  "Type",
];

/** Patterns for detecting generated GraphQL files */
const GENERATED_FILE_PATTERNS = [
  /\.generated\.ts$/,
  /\.generated\.tsx$/,
  /\.generated\.js$/,
  /\.generated\.d\.ts$/,
  /\/generated\//,
  /\/__generated__\//,
  /\/graphql\/.+\.ts$/,
  /graphql\.ts$/,
  /graphql\.tsx$/,
];

/** Markers found in generated GraphQL files */
const GENERATED_MARKERS = [
  "Generated by graphql-codegen",
  "@generated",
  "DO NOT EDIT",
  "This file was automatically generated",
  "eslint-disable",
  "AUTO GENERATED FILE",
  "GraphQL Code Generator",
];

/** Resolver patterns for various frameworks */
const RESOLVER_PATTERNS = [
  // Apollo / type-graphql (TypeScript)
  { pattern: /@Resolver\b/i, framework: "type-graphql" },
  { pattern: /@Query\b/i, framework: "type-graphql" },
  { pattern: /@Mutation\b/i, framework: "type-graphql" },
  { pattern: /@Subscription\b/i, framework: "type-graphql" },
  { pattern: /@FieldResolver\b/i, framework: "type-graphql" },
  // NestJS GraphQL
  { pattern: /@Resolver\(\)/i, framework: "nestjs-graphql" },
  { pattern: /@Query\(\)/i, framework: "nestjs-graphql" },
  { pattern: /@Mutation\(\)/i, framework: "nestjs-graphql" },
  { pattern: /@ResolveField\b/i, framework: "nestjs-graphql" },
  // Strawberry (Python)
  { pattern: /@strawberry\.type\b/i, framework: "strawberry" },
  { pattern: /@strawberry\.mutation\b/i, framework: "strawberry" },
  { pattern: /@strawberry\.subscription\b/i, framework: "strawberry" },
  // HotChocolate (.NET)
  { pattern: /\[QueryType\]/i, framework: "hotchocolate" },
  { pattern: /\[MutationType\]/i, framework: "hotchocolate" },
  { pattern: /\[SubscriptionType\]/i, framework: "hotchocolate" },
  { pattern: /\[ExtendObjectType\]/i, framework: "hotchocolate" },
  // Ariadne (Python)
  { pattern: /@query_type\.field\b/i, framework: "ariadne" },
  { pattern: /@mutation_type\.field\b/i, framework: "ariadne" },
  // GraphQL.js resolvers object
  { pattern: /resolvers\s*[:=]\s*\{/i, framework: "graphql-js" },
];

/** Codegen configuration files for GraphQL */
const CODEGEN_CONFIGS = [
  "codegen.yml",
  "codegen.yaml",
  "codegen.ts",
  "codegen.js",
  ".graphqlrc.yml",
  ".graphqlrc.yaml",
  ".graphqlrc.json",
  ".graphqlrc.js",
  ".graphqlrc.ts",
  "apollo.config.js",
  "apollo.config.ts",
  "graphql.config.js",
  "graphql.config.ts",
  "graphql.config.yml",
  "graphql.config.yaml",
];

// =============================================================================
// MAIN ANALYSIS
// =============================================================================

/**
 * Analyze links between GraphQL schemas and source code
 */
export function analyzeGraphQLCodeLinks(allEntities: Entity[]): GraphQLAnalysis {
  // Separate GraphQL entities from code entities
  const graphqlEntities = allEntities.filter((e) => e.metadata?.["graphqlType"]);
  const codeEntities = allEntities.filter(
    (e) => !e.metadata?.["graphqlType"] && !e.metadata?.["swaggerType"] && !e.metadata?.["protoType"],
  );

  if (graphqlEntities.length === 0) {
    return {
      resolvers: [],
      consumers: [],
      generatedTypes: [],
      generatedFileMarkers: [],
      codegenConfigs: [],
    };
  }

  // Extract GraphQL types for matching
  const graphqlTypes = graphqlEntities.filter(
    (e) =>
      e.metadata?.["graphqlType"] === "type" ||
      e.metadata?.["graphqlType"] === "interface" ||
      e.metadata?.["graphqlType"] === "input" ||
      e.metadata?.["graphqlType"] === "enum",
  );

  const graphqlOperations = graphqlEntities.filter(
    (e) =>
      e.metadata?.["graphqlType"] === "query" ||
      e.metadata?.["graphqlType"] === "mutation" ||
      e.metadata?.["graphqlType"] === "subscription",
  );

  // Detect resolvers (producers)
  const resolvers = detectResolvers(graphqlOperations, graphqlTypes, codeEntities);

  // Detect consumers (generated hooks/queries)
  const consumers = detectConsumers(graphqlOperations, codeEntities);

  // Match generated types
  const generatedTypes = matchGraphQLTypesToCode(graphqlTypes, codeEntities);

  // Find generated file markers
  const generatedFileMarkers = findGeneratedMarkers(codeEntities);

  // Find codegen configs
  const codegenConfigs = findCodegenConfigs(allEntities);

  return {
    resolvers,
    consumers,
    generatedTypes,
    generatedFileMarkers,
    codegenConfigs,
  };
}

/**
 * Build relationships for graph storage
 */
export function buildGraphQLRelationships(analysis: GraphQLAnalysis): GraphQLRelationship[] {
  const relationships: GraphQLRelationship[] = [];

  for (const link of analysis.resolvers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.graphqlEntityName,
      type: RelationType.PRODUCES_API,
      fromFile: link.codeFilePath,
      toFile: link.graphqlFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        typeName: link.graphqlEntityName,
        context: "GraphQL resolver implementation",
      },
    });
  }

  for (const link of analysis.consumers) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.graphqlEntityName,
      type: RelationType.CONSUMES_API,
      fromFile: link.codeFilePath,
      toFile: link.graphqlFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        typeName: link.graphqlEntityName,
        context: "Generated GraphQL consumer",
      },
    });
  }

  for (const link of analysis.generatedTypes) {
    relationships.push({
      fromName: link.codeEntityName,
      toName: link.graphqlEntityName,
      type: RelationType.GENERATED_FROM,
      fromFile: link.codeFilePath,
      toFile: link.graphqlFilePath,
      metadata: {
        confidence: link.confidence,
        evidence: link.evidence,
        typeName: link.graphqlEntityName,
        context: "Generated from GraphQL type",
      },
    });
  }

  return relationships;
}

// =============================================================================
// RESOLVER DETECTION
// =============================================================================

function detectResolvers(
  graphqlOperations: Entity[],
  graphqlTypes: Entity[],
  codeEntities: Entity[],
): GraphQLCodeLink[] {
  const links: GraphQLCodeLink[] = [];
  const allGraphql = [...graphqlOperations, ...graphqlTypes];

  for (const code of codeEntities) {
    const codeText = (code.metadata?.signature as string) ?? code.name;
    const decoratorsMeta = code.metadata?.["decorators"] as Array<{ name: string }> | undefined;
    const decorators = decoratorsMeta?.map((d) => d.name).join(" ") ?? "";
    const fullText = `${codeText} ${decorators}`;
    const evidence: string[] = [];
    let confidence = 0;

    for (const pattern of RESOLVER_PATTERNS) {
      if (pattern.pattern.test(fullText)) {
        evidence.push(`${pattern.framework}: matched pattern ${pattern.pattern.source}`);
        confidence = Math.max(confidence, 0.7);
      }
    }

    if (confidence > 0.3) {
      // Try to match to specific GraphQL type/operation
      const matchedGraphql = findBestGraphQLMatch(code, allGraphql);
      if (matchedGraphql) {
        links.push({
          graphqlEntityName: matchedGraphql.name,
          codeEntityName: code.name,
          codeFilePath: code.filePath,
          graphqlFilePath: matchedGraphql.filePath,
          linkType: "produces_api",
          confidence: Math.min(confidence + 0.1, 1),
          evidence,
        });
      } else {
        // Link to first operation type available
        const target = graphqlOperations[0] ?? graphqlTypes[0];
        if (target) {
          links.push({
            graphqlEntityName: target.name,
            codeEntityName: code.name,
            codeFilePath: code.filePath,
            graphqlFilePath: target.filePath,
            linkType: "produces_api",
            confidence,
            evidence,
          });
        }
      }
    }
  }

  return links;
}

function findBestGraphQLMatch(codeEntity: Entity, graphqlEntities: Entity[]): Entity | null {
  const codeName = codeEntity.name.toLowerCase().replace(/resolver|handler|controller/gi, "");

  for (const gql of graphqlEntities) {
    const gqlName = gql.name.toLowerCase();
    if (codeName === gqlName || codeName.includes(gqlName) || gqlName.includes(codeName)) {
      return gql;
    }
  }

  return null;
}

// =============================================================================
// CONSUMER DETECTION
// =============================================================================

function detectConsumers(graphqlOperations: Entity[], codeEntities: Entity[]): GraphQLCodeLink[] {
  const links: GraphQLCodeLink[] = [];

  for (const code of codeEntities) {
    const isGenerated = GENERATED_FILE_PATTERNS.some((pat) => pat.test(code.filePath));
    if (!isGenerated) continue;

    const evidence: string[] = [`Generated file: ${code.filePath}`];
    let confidence = 0.5;

    // Check for hook patterns (useQuery, useMutation, etc.)
    if (
      code.name.startsWith("use") &&
      (code.name.includes("Query") || code.name.includes("Mutation") || code.name.includes("Subscription"))
    ) {
      evidence.push(`Generated hook: ${code.name}`);
      confidence = 0.8;
    }

    // Check for generated document/operation
    if (code.name.endsWith("Document") || code.name.endsWith("Gql")) {
      evidence.push(`Generated document: ${code.name}`);
      confidence = 0.75;
    }

    // Match to best GraphQL operation
    const matchedOp = findBestOperationMatch(code, graphqlOperations);
    const target = matchedOp ?? graphqlOperations[0];

    if (target) {
      links.push({
        graphqlEntityName: target.name,
        codeEntityName: code.name,
        codeFilePath: code.filePath,
        graphqlFilePath: target.filePath,
        linkType: "consumes_api",
        confidence: Math.min(confidence, 1),
        evidence,
      });
    }
  }

  return links;
}

function findBestOperationMatch(codeEntity: Entity, operations: Entity[]): Entity | null {
  const codeName = codeEntity.name
    .toLowerCase()
    .replace(/^use/, "")
    .replace(/query|mutation|subscription|document|gql$/gi, "");

  for (const op of operations) {
    if (op.name.toLowerCase().includes(codeName) || codeName.includes(op.name.toLowerCase())) {
      return op;
    }
  }

  return null;
}

// =============================================================================
// TYPE MATCHING
// =============================================================================

function matchGraphQLTypesToCode(graphqlTypes: Entity[], codeEntities: Entity[]): GraphQLCodeLink[] {
  const links: GraphQLCodeLink[] = [];
  const codeTypes = codeEntities.filter((e) => e.type === "type" || e.type === "class" || e.type === "interface");

  for (const gqlType of graphqlTypes) {
    const typeName = gqlType.name;
    const strippedGql = stripTypeSuffix(typeName);

    for (const code of codeTypes) {
      const strippedCode = stripTypeSuffix(code.name);
      const evidence: string[] = [];
      let confidence = 0;

      const isGenerated = GENERATED_FILE_PATTERNS.some((pat) => pat.test(code.filePath));

      // Exact name match
      if (code.name === typeName || strippedCode === strippedGql) {
        confidence = isGenerated ? 0.9 : 0.6;
        evidence.push(`Name match: ${code.name} = ${typeName}`);
      }
      // Common generated suffixes
      else if (
        code.name === `${typeName}Type` ||
        code.name === `I${typeName}` ||
        code.name === `${typeName}Model` ||
        code.name === `${typeName}Dto`
      ) {
        confidence = isGenerated ? 0.85 : 0.55;
        evidence.push(`Name match with suffix: ${code.name} ~ ${typeName}`);
      }

      if (isGenerated && confidence > 0) {
        evidence.push(`In generated file: ${code.filePath}`);
      }

      if (confidence > 0.3) {
        links.push({
          graphqlEntityName: typeName,
          codeEntityName: code.name,
          codeFilePath: code.filePath,
          graphqlFilePath: gqlType.filePath,
          linkType: "generated_from",
          confidence: Math.min(confidence, 1),
          evidence,
        });
      }
    }
  }

  return links;
}

// =============================================================================
// GENERATED MARKERS & CODEGEN CONFIGS
// =============================================================================

function findGeneratedMarkers(codeEntities: Entity[]): string[] {
  const markers: string[] = [];

  for (const entity of codeEntities) {
    if (GENERATED_FILE_PATTERNS.some((pat) => pat.test(entity.filePath))) {
      markers.push(entity.filePath);
    }
  }

  return [...new Set(markers)];
}

function findCodegenConfigs(allEntities: Entity[]): string[] {
  const found: string[] = [];

  for (const entity of allEntities) {
    const name = entity.name.toLowerCase();
    const filePath = entity.filePath.toLowerCase();
    if (CODEGEN_CONFIGS.some((cfg) => name === cfg || filePath.endsWith(`/${cfg}`))) {
      found.push(entity.filePath);
    }
  }

  return [...new Set(found)];
}

/** Exported for integration with indexing pipeline */
export function getGraphQLCodegenConfigFiles(): string[] {
  return [...CODEGEN_CONFIGS];
}

/** Exported for integration with indexing pipeline */
export function getGraphQLGeneratedCodeMarkers(): string[] {
  return [...GENERATED_MARKERS];
}

// =============================================================================
// UTILITIES
// =============================================================================

function stripTypeSuffix(name: string): string {
  let result = name;
  for (const suffix of TYPE_SUFFIXES) {
    if (result.endsWith(suffix) && result.length > suffix.length) {
      result = result.slice(0, -suffix.length);
      break;
    }
  }
  return result;
}
